// Code generated by mockery v2.6.0. DO NOT EDIT.

package ingester

import mock "github.com/stretchr/testify/mock"

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measureMetricsParsed provides a mock function with given fields: count
func (_m *MockRecorder) measureMetricsParsed(count int) {
	_m.Called(count)
}
