// Code generated by mockery v2.43.2. DO NOT EDIT.

package remoteread

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measure provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRecorder) measure(_a0 string, _a1 time.Duration, _a2 error) {
	_m.Called(_a0, _a1, _a2)
}

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
