// Code generated by mockery 2.7.4. DO NOT EDIT.

package htstorage

import mock "github.com/stretchr/testify/mock"

// MockCacheRecorder is an autogenerated mock type for the CacheRecorder type
type MockCacheRecorder struct {
	mock.Mock
}

// mcAddErr provides a mock function with given fields:
func (_m *MockCacheRecorder) mcAddErr() {
	_m.Called()
}

// mcAddNotStored provides a mock function with given fields:
func (_m *MockCacheRecorder) mcAddNotStored() {
	_m.Called()
}

// mcAddTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) mcAddTotal() {
	_m.Called()
}

// mcDeleteAfterFailedSetErr provides a mock function with given fields:
func (_m *MockCacheRecorder) mcDeleteAfterFailedSetErr() {
	_m.Called()
}

// mcDeleteAfterFailedSetMiss provides a mock function with given fields:
func (_m *MockCacheRecorder) mcDeleteAfterFailedSetMiss() {
	_m.Called()
}

// mcDeleteAfterFailedSetTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) mcDeleteAfterFailedSetTotal() {
	_m.Called()
}

// mcDeleteAfterFailedUnmarshalErr provides a mock function with given fields:
func (_m *MockCacheRecorder) mcDeleteAfterFailedUnmarshalErr() {
	_m.Called()
}

// mcDeleteAfterFailedUnmarshalMiss provides a mock function with given fields:
func (_m *MockCacheRecorder) mcDeleteAfterFailedUnmarshalMiss() {
	_m.Called()
}

// mcDeleteAfterFailedUnmarshalTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) mcDeleteAfterFailedUnmarshalTotal() {
	_m.Called()
}

// mcGetErr provides a mock function with given fields:
func (_m *MockCacheRecorder) mcGetErr() {
	_m.Called()
}

// mcGetMiss provides a mock function with given fields:
func (_m *MockCacheRecorder) mcGetMiss() {
	_m.Called()
}

// mcGetTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) mcGetTotal() {
	_m.Called()
}

// mcSetErr provides a mock function with given fields:
func (_m *MockCacheRecorder) mcSetErr() {
	_m.Called()
}

// mcSetTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) mcSetTotal() {
	_m.Called()
}

// missingOrgID provides a mock function with given fields:
func (_m *MockCacheRecorder) missingOrgID() {
	_m.Called()
}

// storageGetErr provides a mock function with given fields:
func (_m *MockCacheRecorder) storageGetErr() {
	_m.Called()
}

// storageGetNotFound provides a mock function with given fields:
func (_m *MockCacheRecorder) storageGetNotFound() {
	_m.Called()
}

// storageGetTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) storageGetTotal() {
	_m.Called()
}

// storageSetErr provides a mock function with given fields:
func (_m *MockCacheRecorder) storageSetErr() {
	_m.Called()
}

// storageSetTotal provides a mock function with given fields:
func (_m *MockCacheRecorder) storageSetTotal() {
	_m.Called()
}

// unmarshalError provides a mock function with given fields:
func (_m *MockCacheRecorder) unmarshalError() {
	_m.Called()
}
