// Code generated by mockery 2.7.4. DO NOT EDIT.

package htstorage

import mock "github.com/stretchr/testify/mock"

// MockCacheKeygen is an autogenerated mock type for the CacheKeygen type
type MockCacheKeygen struct {
	mock.Mock
}

// HostKey provides a mock function with given fields: orgID, hostName
func (_m *MockCacheKeygen) HostKey(orgID string, hostName string) string {
	ret := _m.Called(orgID, hostName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(orgID, hostName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
