// Code generated by mockery 2.7.4. DO NOT EDIT.

package remotewrite

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measure provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRecorder) measure(_a0 string, _a1 time.Duration, _a2 error) {
	_m.Called(_a0, _a1, _a2)
}

// measureOutOfOrderSamples provides a mock function with given fields: count
func (_m *MockRecorder) measureOutOfOrderSamples(count int) {
	_m.Called(count)
}
