package ddprom

var (
	// Internal labels and metrics generated by the proxy.

	DDTypeLabel          = MakeInternalLabelName("dd_type")
	HostLabelName        = MakeInternalLabelName("host")
	AllHostTagsLabelName = MakeInternalLabelName("all_host_tags")

	HostTagsMetricName = MakeInternalMetricName("hosttags")
)
