// Code generated by mockery v2.14.0. DO NOT EDIT.

package writeproxy

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measureConversionDuration provides a mock function with given fields: user, duration
func (_m *MockRecorder) measureConversionDuration(user string, duration time.Duration) {
	_m.Called(user, duration)
}

// measureIncomingRequest provides a mock function with given fields: user
func (_m *MockRecorder) measureIncomingRequest(user string) {
	_m.Called(user)
}

// measureIncomingSamples provides a mock function with given fields: user, count
func (_m *MockRecorder) measureIncomingSamples(user string, count int) {
	_m.Called(user, count)
}

// measureReceivedRequest provides a mock function with given fields: user
func (_m *MockRecorder) measureReceivedRequest(user string) {
	_m.Called(user)
}

// measureReceivedSamples provides a mock function with given fields: user, count
func (_m *MockRecorder) measureReceivedSamples(user string, count int) {
	_m.Called(user, count)
}

// measureRejectedSamples provides a mock function with given fields: user, reason
func (_m *MockRecorder) measureRejectedSamples(user string, reason string) {
	_m.Called(user, reason)
}

type mockConstructorTestingTNewMockRecorder interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRecorder(t mockConstructorTestingTNewMockRecorder) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
