// Code generated by mockery 2.7.4. DO NOT EDIT.

package writeproxy

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

// measureConversionDuration provides a mock function with given fields: user, duration
func (_m *MockRecorder) measureConversionDuration(user string, duration time.Duration) {
	_m.Called(user, duration)
}

// measureIncomingSamples provides a mock function with given fields: user, count
func (_m *MockRecorder) measureIncomingSamples(user string, count int) {
	_m.Called(user, count)
}

// measureReceivedSamples provides a mock function with given fields: user, count
func (_m *MockRecorder) measureReceivedSamples(user string, count int) {
	_m.Called(user, count)
}

// measureRejectedSamples provides a mock function with given fields: user, reason
func (_m *MockRecorder) measureRejectedSamples(user string, reason string) {
	_m.Called(user, reason)
}
